version: "3"
services:
  node-app:
    build: .
    ports:
      - "3001:4001"
    environment:
      - PORT=4001
  mongo:
    image: mongo
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=sangha18012001
      - MONGO_INITDB_ROOT_PASSWORD=YYjkvIdXJ1YLbj3A
    volumes:
      - mongo-db:/data/db
volumes:
  mongo-db: